name: Build and Release Installer

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build FileMoverService
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up .NET
    - name: Set up .NET 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "9.0"

    # Step 3: Restore dependencies and build
    - name: Restore and Build
      run: |
        dotnet restore
        dotnet publish -c Release -o publish

    # Step 4: Build the Installer with Inno Setup
    - name: Build Installer
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer/FileMoverService.iss

    # Step 5: Upload Installer to Release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: FileMoverServiceInstaller.exe
        asset_name: FileMoverServiceInstaller.exe
        content_type: application/octet-stream
